Added legend to MAD styles.
digitalearthafrica/config pull request #198
Opened 2021-05-19 00:25 UTC by eefaye

Just would like to check it is acceptable to set the URL as the S3 link: `"url": "s3://deafrica-services/gm_s2_annual/gm_s2_annual_legend.png"`

2021-05-19 03:15 UTC, pindge approved these changes

2021-05-19 03:15 UTC, pindge commented on services/ows_refactored/surface_reflectance/style_sr_cfg.py
> +        "url": "s3://deafrica-services/gm_s2_annual/gm_s2_annual_legend.png",
please us https/http link for terria to fetch, has to be publicly readable

2021-05-19 03:16 UTC, pindge requested changes
please upate both links

2021-05-20 02:28 UTC, eefaye commented
@pindge  URLs have been updated to the https link provided by Alex.

2021-05-21 03:08 UTC, whatnick approved these changes

2021-05-21 03:08 UTC, merged