OWS styles for Landsat C2 data
digitalearthafrica/config pull request #199
Opened 2021-05-20 01:47 UTC by eefaye

Changed files:
 * `style_sr_cfg.py`: 11 styles added for `lsc2_sr`, compiled in a new styles list `styles_lsc2_sr_list`. Scaling has been changed from 0-10000 to 1-65455 and existing ranges scaled accordingly
 * `band_sr_cfg.py`: Common Landsat bands added to a new band list `bands_lsc2_sr` *note it is the same as the `bands_ls` list but so far has been separated so the old Landsat configs can be reorganised on a different occasion*
 * `ows_sr_cfg.py`: "Collection 1" mentions upgraded to "Collection 2". "Five countries" replaced with "all Africa". Style and band list references updated to the new ones mentioned above

**To be added:** `ls_st` configs for surface temperature

Submitting the PR now for review. I expect some whitespace is causing issues but would like to check nothing else is.

2021-05-20 07:49 UTC, eefaye commented
@SpacemanPaul if you could review if this is the correct usage of `index_expression` that would be much appreciated!

2021-05-20 23:29 UTC, fangfy commented on services/ows_refactored/surface_reflectance/style_sr_cfg.py
> +    "index_expression": "((nir-55000)-(red-55000))/((nir-55000)+(red-55000))",
Should it be 55000? or 0.2/2.75e-5?

2021-05-20 23:31 UTC, fangfy requested changes
Fix whitespace and check offset for index calculation. Otherwise looks good.

2021-05-21 06:54 UTC, fangfy approved these changes
This looks good to me. But I don't know what's the build error about.

2021-05-24 02:10 UTC, fangfy approved these changes

2021-05-24 02:11 UTC, merged