WOfS Alchemist YAML for USGS Collection 2 Landsat
digitalearthafrica/config pull request #201
Opened 2021-05-24 04:31 UTC by eloise-b

2021-05-24 05:49 UTC, alexgleith requested changes
Can we please name this like the final product, so <product_name>.alchemist.yaml.

Other comments throughout.

2021-05-24 05:49 UTC, alexgleith commented on dev/alchemist/DEAfrica_wofs_c2.yaml
> +  #measurements: ['nbart_blue', 'nbart_green', 'nbart_red', 'nbart_nir', 'nbart_swir_1', 'nbart_swir_2', 'oa_fmask']
Let's remove this :-)

2021-05-24 05:49 UTC, alexgleith commented on dev/alchemist/DEAfrica_wofs_c2.yaml
> +    #dsm_path:  'https://deafrica-data.s3-us-west-2.amazonaws.com/ancillary/dem/srtm_africa.tif' #'s3://deafrica-data/ancillary/dem/srtm_africa.tif'
Let's remove this too please

2021-05-24 05:49 UTC, alexgleith commented on dev/alchemist/DEAfrica_wofs_c2.yaml
> +  location: '/home/jovyan/Alchemist/' #'s3://deafrica-data-dev/wofs/new'
```suggestion
  location: s3://deafrica-data-dev-af/
```

2021-05-24 05:49 UTC, alexgleith commented on dev/alchemist/DEAfrica_wofs_c2.yaml
> +  explorer_url: https://explorer.dev.digitalearth.africa/products/ls8_c2l2/extents
Can we make this the right name, whatever product it is that is the result...

2021-05-24 05:49 UTC, alexgleith commented on dev/alchemist/DEAfrica_wofs_c2.yaml
> +#    n_workers: 4
Remove please

2021-05-24 05:49 UTC, alexgleith commented on dev/alchemist/DEAfrica_wofs_c2.yaml
> +    y: 600
Let's change these, like this: https://github.com/GeoscienceAustralia/dea-config/blob/master/dev/services/alchemist/ga_ls_wo_3/ga_ls_wo_3.alchemist.yaml

2021-05-24 08:25 UTC, fangfy commented
@eloise-b forgot to mention that I've also made a few changes in the version you made in the scripts repo. Have a look there and we should also clean that repo up I think.

2021-05-24 09:38 UTC, alexgleith commented
We should probably clean this repo up a bit too! Todo: ...

2021-05-25 04:17 UTC, eloise-b reviewed
These changes have been completed.

2021-05-31 06:07 UTC, merged