Landsat 5/7/8 surface temperature layers
digitalearthafrica/config pull request #210
Opened 2021-05-28 05:59 UTC by eefaye

2021-05-28 06:13 UTC, eefaye commented
@fangfy , not sure why the `isort` check is failing. 
@SpacemanPaul a review of the `ows_lsc2_st_cfg.py` file would be much appreciated (other ones as well but that one is the most likely to have issues...) I have used `"mpl_ramp"`, just wondering there is no need to import `matplotlib` or anything like that?

2021-05-28 06:26 UTC, fangfy requested changes

2021-05-28 06:26 UTC, fangfy commented on services/ows_refactored/surface_temperature/ows_lsc2_st_cfg.py
> +    "name": "ls8_st",
should be ls7_st

2021-06-01 01:36 UTC, SpacemanPaul commented on services/ows_refactored/surface_temperature/ows_lsc2_st_cfg.py
> +    "mpl_ramp": "magma",
I think this is your problem.  If you want to use `mpl_ramp`, you must also set the `range`.

2021-06-01 01:58 UTC, fangfy approved these changes

2021-06-01 01:58 UTC, merged