Western cropmask
digitalearthafrica/config pull request #263
Opened 2021-08-30 11:56 UTC by eefaye

- Added western crop mask layer to crop mask `cfg.py` file
- Added western crop mask layer to `dev` inventory json
- Removed Oregon `root_cfg` - to check
- Updated ows_refactored README

2021-08-31 02:57 UTC, eefaye commented
@fangfy @alexgleith The build failure is caused by the western crop mask not being added to the prod inventory. Can we check it runs in dev first before committing to prod?

@alexgleith  could you please confirm the Oregon `root_cfg` file can be removed?
Additionally, I would like to check which of these files is active:
`config/services/deafrica_prod_af.ows_cfg.py` 
or
`config/services/ows_cfg.py`
and if one can be removed.

2021-08-31 05:32 UTC, fangfy commented on services/ows_refactored/agriculture/ows_crop_mask_cfg.py
> +This provisional cropland extent map has a resolution of 10m, and was built using Copernicus Sentinel-2 satellite images from 2019 and 2020. The cropland extent map was produced using extensive train
while you are at it, can you remove 2020 from the description?

2021-08-31 05:34 UTC, fangfy commented on services/ows_refactored/agriculture/ows_crop_mask_cfg.py
> +This provisional cropland extent map has a resolution of 10m, and was built using Copernicus Sentinel-2 satellite images from 2019 and 2020. The cropland extent map was produced using extensive train
should be 2019 only as well.

2021-08-31 05:36 UTC, fangfy commented on services/ows_refactored/prod_af_ows_root_cfg.py
> +                            "include": "ows_refactored.agriculture.ows_crop_mask_cfg.layers",
This makes the layer available in prod, so you probably need to update the inventory for prod as well.

2021-08-31 05:38 UTC, fangfy commented on services/ows_refactored/agriculture/ows_crop_mask_cfg.py
> +            "title": "Cropland extent map - Eastern Africa",
now that we only have 2019, can you add 2019 to the product title? otherwise it's not easy for the user to tell which year this is for.

2021-08-31 05:39 UTC, fangfy requested changes
see inline comments.

2021-09-06 02:30 UTC, fangfy approved these changes

2021-09-06 02:30 UTC, merged