Add coastlines 4
digitalearthafrica/config pull request #440
Opened 2022-09-27 13:18 UTC by lgkgh

2022-09-27 14:40 UTC, SeffatChowdhury commented
@lgkgh some attribute names changed, so the config needs updates. Will commit into this branch

2022-09-28 13:54 UTC, SeffatChowdhury commented
@leon tests passing now

2022-09-29 02:04 UTC, robbibt commented
Hi all, I was going to send a message with more detail on this, but FYI the following fields have been changed or added in this version:

Hotspots layers:
![image](https://user-images.githubusercontent.com/17680388/192921707-b5aed239-ac04-4eab-a4ca-28607a0847af.png)

Rates of change layer:
![image](https://user-images.githubusercontent.com/17680388/192921893-73286a9d-a436-4cc6-9e70-80b1050c5d17.png)

2022-09-29 06:32 UTC, SeffatChowdhury commented
Thanks @robbibt ! Once this is reviewed and merged, we can modify the SLDs to use the wms_* fields

2022-09-29 06:57 UTC, robbibt commented
@SeffatChowdhury Sounds good - let me know when this is merged and live on `dev`, and I can raise a new PR to edit the SLDs to use the new fields. 😃

2022-09-29 07:02 UTC, SeffatChowdhury requested changes

2022-09-29 07:02 UTC, SeffatChowdhury commented on geoserver/geoserver_data/collections/coastline_v0.4.0/layergroups/DEACoastlines.json
> +        "name": "DEACoastlines 0.4.0",
@lgkgh I think we need to effect the name change here?

2022-10-05 07:45 UTC, SeffatChowdhury approved these changes

2022-10-05 17:38 UTC, merged